---
- name: Install CryptoPro Csp
  hosts: localhost
  become: true
  vars:
    cp_path: /opt/cprocsp/sbin/amd64/

  tasks:

    - name: Unarchive CryptoPro CSP v5
      ansible.builtin.unarchive:
        src: /tmp/linux-amd64_deb.tgz
        dest: /tmp/

    - name: Start script in archive
      ansible.builtin.shell: /tmp/linux-amd64_deb/install.sh
      

    - name: Create simlinks
      ansible.builtin.shell: |
        ln -s {{ cp_path }}certmgr certmgr
        ln -s {{ cp_path }}cpverify cpverify
        ln -s {{ cp_path }}cryptcp cryptcp
        ln -s {{ cp_path }}csptest csptest 
        ln -s {{ cp_path }}csptestf csptestf
        ln -s {{ cp_path }}der2xer der2xer
        ln -s {{ cp_path }}inittst inittst
        ln -s {{ cp_path }}wipefile wipefile
        ln -s {{ cp_path }}cpconfig cpconfig

    - name: Check version CryptoPro
      ansible.builtin.shell: "{{ cp_path }}csptestf -enum -info"
      register: cp_version

    - name: Check license CryptoPro
      ansible.builtin.shell: "{{ cp_path }}cpconfig -license -view"
      register: cp_license


    - name: Get CryptoPro version
      ansible.builtin.debug:
        var: cp_version.stdout_lines
    
    - name: Get CryptoPro license
      ansible.builtin.debug:
        var: cp_license.stdout_lines