---
- name: Install CryptoPro Csp
  hosts: localhost
  become: true


  tasks:

    - name: Unarchive CryptoPro CSP v5
      ansible.builtin.unarchive:
        src: /tmp/linux-amd64_deb.tgz
        dest: /tmp/

    - name: Start script in archive
      ansible.builtin.shell: /tmp/linux-amd64_deb/install.sh
      

    - name: Create simlinks
      ansible.builtin.shell: |
        ln -s /opt/cprocsp/bin/amd64/certmgr
        ln -s /opt/cprocsp/bin/amd64/cpverify
        ln -s /opt/cprocsp/bin/amd64/cryptcp
        ln -s /opt/cprocsp/bin/amd64/csptest
        ln -s /opt/cprocsp/bin/amd64/csptestf
        ln -s /opt/cprocsp/bin/amd64/der2xer
        ln -s /opt/cprocsp/bin/amd64/inittst
        ln -s /opt/cprocsp/bin/amd64/wipefile
        ln -s /opt/cprocsp/sbin/amd64/cpconfig

    - name: Check version CryptoPro
      ansible.builtin.shell: csptestf -enum -info
      register: cp_version

    - name: Check license CryptoPro
      ansible.builtin.shell: cpconfig -license -view
      register: cp_license


    - name: Get CryptoPro version
      ansible.builtin.debug:
        var: cp_version.stdout_lines
    
    - name: Get CryptoPro license
      ansible.builtin.debug:
        var: cp_license.stdout_lines